### ISSUE TITLE
pixel-ratio

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/alice-perl-eerl-urbtrees#16]
@ymarcon @sphamba 
I talked with Aurèle this morning, and my intuition is that because we're using mac book with high-dpi screen. We may have a scaling problem with maplibre.

By googling a bit I found two issues/pull-rrequest. I don't have more time to investigate though.
https://github.com/maplibre/maplibre-gl-js/issues/769
https://github.com/maplibre/maplibre-gl-js/pull/772
cf the screen shot for information
![pixel-ratio](https://github.com/EPFL-ENAC/alice-perl-eerl-urbtrees/assets/161889/e0dec507-6eb2-4fec-a0e7-06e9ce96190e)

**Comment by ymarcon** [comment]
yes looks like much more fuzzy that what I had
